"""
Build full 26-man squad data for all 48 World Cup 2026 teams.
Merges existing 147 players + adds ~20 per team from official squad lists.
Estimated stats for backup/bench players based on position and club level.
"""

import json, copy

DATA_DIR = "data"

def load_json(name):
    with open(f"{DATA_DIR}/{name}", "r", encoding="utf-8") as f:
        return json.load(f)

# Load existing data
wp = load_json("world_cup_players.json")
supp = load_json("player_stats_supplement.json")

# Build lookup of existing players
existing = {}
for gn, gd in wp["groups"].items():
    for nat, td in gd["teams"].items():
        for p in td["players"]:
            existing[(p["name"], nat)] = p

# Mark which players are already in the data
def has_player(nat, name):
    return (name, nat) in existing

# ============================================================
# FULL SQUAD DATA — organized by group
# ============================================================
# Format: {nation: [(name, position, club, league, goals_2526, assists_2526, rating, notes)]}

SQUADS = {
    # === GROUP A ===
    "Mexico": [
        ("Guillermo Ochoa", "GK", "—", "—", 0, 0, 6.5, "6th World Cup"),
        ("Luis Malagón", "GK", "América", "Liga MX", 0, 0, 6.3, ""),
        ("Carlos Acevedo", "GK", "Santos Laguna", "Liga MX", 0, 0, 6.2, ""),
        ("Edson Álvarez", "MF", "West Ham", "Premier League", 2, 2, 7.0, "Captain"),
        ("César Montes", "DF", "Almería", "La Liga", 1, 0, 6.7, ""),
        ("Johan Vásquez", "DF", "Genoa", "Serie A", 1, 1, 6.8, ""),
        ("Jorge Sánchez", "DF", "Porto", "Liga Portugal", 0, 2, 6.6, ""),
        ("Gerardo Arteaga", "DF", "Monterrey", "Liga MX", 1, 3, 6.7, ""),
        ("Jesús Gallardo", "DF", "Monterrey", "Liga MX", 0, 1, 6.5, ""),
        ("Israel Reyes", "DF", "América", "Liga MX", 0, 0, 6.5, ""),
        ("Luis Romo", "MF", "Cruz Azul", "Liga MX", 3, 2, 6.8, ""),
        ("Orbelín Pineda", "MF", "AEK Athens", "Greek Super League", 4, 3, 6.9, ""),
        ("Carlos Rodríguez", "MF", "Cruz Azul", "Liga MX", 2, 4, 6.8, ""),
        ("Érick Sánchez", "MF", "América", "Liga MX", 3, 3, 6.7, ""),
        ("Sebastián Córdova", "MF", "Tigres", "Liga MX", 5, 4, 7.0, ""),
        ("Roberto Alvarado", "MF", "Guadalajara", "Liga MX", 4, 5, 6.9, ""),
        ("Santiago Giménez", "FW", "Feyenoord", "Eredivisie", 15, 3, 7.2, ""),
        ("Raúl Jiménez", "FW", "Fulham", "Premier League", 9, 2, 7.0, ""),
        ("Hirving Lozano", "FW", "PSV", "Eredivisie", 7, 4, 6.9, ""),
        ("Gilberto Mora", "FW", "Tijuana", "Liga MX", 4, 3, 6.7, "Youngest player 17y"),
        ("Alexis Vega", "FW", "Toluca", "Liga MX", 6, 3, 6.8, ""),
        ("Uriel Antuna", "FW", "Cruz Azul", "Liga MX", 5, 5, 6.9, ""),
    ],
    "South Africa": [
        ("Ronwen Williams", "GK", "Mamelodi Sundowns", "—", 0, 0, 6.7, "Captain"),
        ("Veli Mothwa", "GK", "AmaZulu", "—", 0, 0, 6.2, ""),
        ("Ricardo Goss", "GK", "SuperSport United", "—", 0, 0, 6.1, ""),
        ("Siyanda Xulu", "DF", "SuperSport United", "—", 0, 0, 6.3, ""),
        ("Mothobi Mvala", "DF", "Mamelodi Sundowns", "—", 1, 0, 6.4, ""),
        ("Aubrey Modiba", "DF", "Mamelodi Sundowns", "—", 0, 2, 6.5, ""),
        ("Khuliso Mudau", "DF", "Mamelodi Sundowns", "—", 0, 1, 6.4, ""),
        ("Grant Kekana", "DF", "Mamelodi Sundowns", "—", 0, 0, 6.3, ""),
        ("Njabulo Blom", "DF", "Kaizer Chiefs", "—", 0, 1, 6.3, ""),
        ("Teboho Mokoena", "MF", "Mamelodi Sundowns", "—", 3, 2, 6.7, ""),
        ("Sphephelo Sithole", "MF", "Tondela", "—", 1, 1, 6.3, ""),
        ("Themba Zwane", "FW", "Mamelodi Sundowns", "—", 4, 3, 6.6, ""),
        ("Percy Tau", "FW", "Al Ahly", "—", 5, 4, 6.7, ""),
        ("Lyle Foster", "FW", "Burnley", "Premier League", 6, 2, 6.7, ""),
        ("Bongokuhle Hlongwane", "FW", "Minnesota United", "MLS", 5, 2, 6.6, ""),
        ("Mihlali Mayambela", "FW", "Aris Limassol", "—", 3, 2, 6.4, ""),
        ("Evidence Makgopa", "FW", "Orlando Pirates", "—", 4, 1, 6.5, ""),
    ],
    "South Korea": [
        ("Kim Seung-gyu", "GK", "Al Shabab", "Saudi Pro League", 0, 0, 6.5, ""),
        ("Jo Hyeon-woo", "GK", "Ulsan HD", "K League 1", 0, 0, 6.3, ""),
        ("Song Bum-keun", "GK", "Jeonbuk", "K League 1", 0, 0, 6.2, ""),
        ("Kim Min-jae", "DF", "Bayern Munich", "Bundesliga", 2, 1, 7.2, ""),
        ("Kim Young-gwon", "DF", "Ulsan HD", "K League 1", 0, 0, 6.5, ""),
        ("Jung Seung-hyun", "DF", "Ulsan HD", "K League 1", 0, 0, 6.4, ""),
        ("Seol Young-woo", "DF", "Ulsan HD", "K League 1", 0, 2, 6.6, ""),
        ("Kim Tae-hwan", "DF", "Jeonbuk", "K League 1", 0, 1, 6.4, ""),
        ("Lee Ki-je", "DF", "Suwon", "K League 1", 1, 2, 6.5, ""),
        ("Jens Castrop", "MF", "FC Nürnberg", "2. Bundesliga", 2, 2, 6.5, "First dual-heritage player"),
        ("Hwang In-beom", "MF", "Crvena zvezda", "Serbian SuperLiga", 3, 3, 6.8, ""),
        ("Lee Jae-sung", "MF", "Mainz", "Bundesliga", 4, 3, 6.9, ""),
        ("Paik Seung-ho", "MF", "Birmingham City", "Championship", 2, 2, 6.6, ""),
        ("Jung Woo-young", "MF", "Al Khaleej", "Saudi Pro League", 1, 1, 6.4, ""),
        ("Son Heung-min", "FW", "Tottenham", "Premier League", 17, 9, 7.5, "Captain"),
        ("Lee Kang-in", "FW", "PSG", "Ligue 1", 6, 7, 7.1, ""),
        ("Hwang Hee-chan", "FW", "Wolves", "Premier League", 8, 3, 7.0, "Bull"},
        ("Cho Gue-sung", "FW", "Midtjylland", "Danish Superliga", 7, 2, 6.8, ""),
        ("Oh Hyeon-gyu", "FW", "Celtic", "Scottish Premiership", 6, 1, 6.7, ""),
    ],
    "Czech Republic": [
        ("Jindřich Staněk", "GK", "Slavia Praha", "Czech First League", 0, 0, 6.5, ""),
        ("Matěj Kovář", "GK", "Bayer Leverkusen", "Bundesliga", 0, 0, 6.4, ""),
        ("Tomáš Vaclík", "GK", "Albacete", "—", 0, 0, 6.3, ""),
        ("Vladimír Coufal", "DF", "West Ham", "Premier League", 0, 3, 6.8, ""),
        ("Jakub Brabec", "DF", "Aris Thessaloniki", "Greek Super League", 1, 0, 6.5, ""),
        ("Ladislav Krejčí", "DF", "Sparta Praha", "Czech First League", 1, 0, 6.6, ""),
        ("David Zima", "DF", "Torino", "Serie A", 0, 0, 6.5, ""),
        ("Jaroslav Zelený", "DF", "Sparta Praha", "Czech First League", 0, 1, 6.4, ""),
        ("Martin Vitík", "DF", "Sparta Praha", "Czech First League", 0, 0, 6.4, ""),
        ("Tomáš Souček", "MF", "West Ham", "Premier League", 3, 3, 7.0, "Captain"),
        ("Alex Král", "MF", "Union Berlin", "Bundesliga", 1, 1, 6.5, ""),
        ("Michal Sadílek", "MF", "Twente", "Eredivisie", 2, 2, 6.6, ""),
        ("Antonín Barák", "MF", "Fiorentina", "Serie A", 3, 2, 6.7, ""),
        ("Lukáš Provod", "MF", "Slavia Praha", "Czech First League", 2, 3, 6.6, ""),
        ("Ondřej Lingr", "MF", "Feyenoord", "Eredivisie", 2, 2, 6.5, ""),
        ("Patrik Schick", "FW", "Bayer Leverkusen", "Bundesliga", 16, 3, 7.1, ""),
        ("Adam Hložek", "FW", "Bayer Leverkusen", "Bundesliga", 5, 3, 6.8, ""),
        ("Tomáš Čvančara", "FW", "Borussia Mönchengladbach", "Bundesliga", 4, 2, 6.7, ""),
        ("Jan Kuchta", "FW", "Sparta Praha", "Czech First League", 6, 2, 6.7, ""),
    ],

    # === GROUP B ===
    "Canada": [
        ("Maxime Crépeau", "GK", "LAFC", "MLS", 0, 0, 6.3, ""),
        ("Dayne St. Clair", "GK", "Minnesota United", "MLS", 0, 0, 6.3, ""),
        ("Jonathan Sirois", "GK", "CF Montréal", "MLS", 0, 0, 6.1, ""),
        ("Alphonso Davies", "DF", "Bayern Munich", "Bundesliga", 3, 6, 7.3, "Captain"),
        ("Alistair Johnston", "DF", "Celtic", "Scottish Premiership", 1, 3, 6.8, ""),
        ("Richie Laryea", "DF", "Toronto FC", "MLS", 0, 2, 6.6, ""),
        ("Kamal Miller", "DF", "Inter Miami", "MLS", 0, 0, 6.5, ""),
        ("Derek Cornelius", "DF", "Malmö FF", "Swedish Allsvenskan", 1, 0, 6.5, ""),
        ("Luc de Fougerolles", "DF", "Fulham", "Premier League", 0, 0, 6.3, ""),
        ("Sam Adekugbe", "DF", "Vancouver Whitecaps", "MLS", 0, 1, 6.4, ""),
        ("Stephen Eustáquio", "MF", "LAFC", "MLS", 3, 3, 6.9, ""),
        ("Ismaël Koné", "MF", "Watford", "Championship", 2, 2, 6.7, ""),
        ("Jonathan Osorio", "MF", "Toronto FC", "MLS", 4, 2, 6.6, ""),
        ("Mathieu Choinière", "MF", "CF Montréal", "MLS", 2, 3, 6.5, ""),
        ("Tajon Buchanan", "FW", "Inter Milan", "Serie A", 3, 3, 6.8, ""),
        ("Jonathan David", "FW", "Lille", "Ligue 1", 17, 4, 7.3, ""),
        ("Cyle Larin", "FW", "Mallorca", "La Liga", 9, 3, 6.9, ""),
        ("Liam Millar", "FW", "Preston", "Championship", 4, 3, 6.6, ""),
        ("Jacen Russell-Rowe", "FW", "Columbus Crew", "MLS", 5, 2, 6.5, ""),
    ],
    "Bosnia-Herzegovina": [
        ("Ibrahim Šehić", "GK", "Al Wehda", "Saudi Pro League", 0, 0, 6.3, ""),
        ("Nikola Vasilj", "GK", "St. Pauli", "Bundesliga", 0, 0, 6.2, ""),
        ("Sead Kolašinac", "DF", "Atalanta", "Serie A", 1, 1, 6.8, ""),
        ("Anel Ahmedhodžić", "DF", "Sheffield United", "Championship", 1, 0, 6.6, ""),
        ("Dennis Hadžikadunić", "DF", "Hamburger SV", "Bundesliga", 0, 0, 6.4, ""),
        ("Jusuf Gazibegović", "DF", "Sturm Graz", "Austrian Bundesliga", 0, 1, 6.4, ""),
        ("Amar Dedić", "DF", "RB Salzburg", "Austrian Bundesliga", 1, 2, 6.6, ""),
        ("Miralem Pjanić", "MF", "Sharjah FC", "UAE League", 2, 4, 6.7, ""),
        ("Rade Krunić", "MF", "Fenerbahçe", "Turkish Super Lig", 2, 2, 6.6, ""),
        ("Gojko Cimirot", "MF", "Al Feiha", "Saudi Pro League", 1, 1, 6.4, ""),
        ("Benjamin Tahirović", "MF", "Ajax", "Eredivisie", 1, 2, 6.5, ""),
        ("Amar Rahmanović", "MF", "Krylya Sovetov", "Russian PL", 2, 1, 6.4, ""),
        ("Edin Džeko", "FW", "Fenerbahçe", "Turkish Super Lig", 8, 3, 7.0, "40yo captain"),
        ("Ermedin Demirović", "FW", "VfB Stuttgart", "Bundesliga", 10, 3, 7.0, ""),
        ("Luka Menalo", "FW", "Dinamo Zagreb", "Croatian HNL", 3, 2, 6.4, ""),
        ("Smail Prevljak", "FW", "Hertha BSC", "Bundesliga", 4, 1, 6.5, ""),
    ],
    "Qatar": [
        ("Meshaal Barsham", "GK", "Al Sadd", "Qatar Stars League", 0, 0, 6.2, ""),
        ("Salah Zakaria", "GK", "Al Duhail", "Qatar Stars League", 0, 0, 6.0, ""),
        ("Tarek Salman", "DF", "Al Sadd", "Qatar Stars League", 0, 0, 6.2, ""),
        ("Boualem Khoukhi", "DF", "Al Sadd", "Qatar Stars League", 1, 0, 6.3, ""),
        ("Abdelkarim Hassan", "DF", "Al Sadd", "Qatar Stars League", 0, 1, 6.4, ""),
        ("Homam Ahmed", "DF", "Al Duhail", "Qatar Stars League", 0, 1, 6.3, ""),
        ("Sultan Al-Brake", "DF", "Al Duhail", "Qatar Stars League", 0, 0, 6.2, ""),
        ("Jassem Gaber", "DF", "Al Arabi", "Qatar Stars League", 0, 0, 6.2, ""),
        ("Abdulaziz Hatem", "MF", "Al Rayyan", "Qatar Stars League", 2, 2, 6.5, ""),
        ("Ali Assadalla", "MF", "Al Sadd", "Qatar Stars League", 1, 2, 6.4, ""),
        ("Mostafa Meshaal", "MF", "Al Sadd", "Qatar Stars League", 2, 1, 6.4, ""),
        ("Ahmed Fathy", "MF", "Al Arabi", "Qatar Stars League", 1, 1, 6.3, ""),
        ("Akram Afif", "FW", "Al Sadd", "Qatar Stars League", 8, 6, 6.8, "Asian POTY"),
        ("Almoez Ali", "FW", "Al Duhail", "Qatar Stars League", 7, 2, 6.7, ""),
        ("Yusuf Abdurisag", "FW", "Al Sadd", "Qatar Stars League", 3, 2, 6.3, ""),
        ("Ahmed Alaaeldin", "FW", "Al Duhail", "Qatar Stars League", 2, 1, 6.2, ""),
    ],
    "Switzerland": [
        ("Gregor Kobel", "GK", "Borussia Dortmund", "Bundesliga", 0, 0, 7.2, ""),
        ("Yann Sommer", "GK", "Inter Milan", "Serie A", 0, 0, 7.0, ""),
        ("Yvon Mvogo", "GK", "Lorient", "Ligue 1", 0, 0, 6.3, ""),
        ("Manuel Akanji", "DF", "Manchester City", "Premier League", 1, 1, 7.0, ""),
        ("Nico Elvedi", "DF", "Borussia Mönchengladbach", "Bundesliga", 1, 0, 6.7, ""),
        ("Ricardo Rodríguez", "DF", "Torino", "Serie A", 0, 2, 6.7, ""),
        ("Silvan Widmer", "DF", "Mainz", "Bundesliga", 0, 2, 6.6, ""),
        ("Eray Cömert", "DF", "Valencia", "La Liga", 0, 0, 6.5, ""),
        ("Cédric Zesiger", "DF", "Wolfsburg", "Bundesliga", 0, 0, 6.4, ""),
        ("Granit Xhaka", "MF", "Bayer Leverkusen", "Bundesliga", 3, 5, 7.2, "Captain"),
        ("Remo Freuler", "MF", "Bologna", "Serie A", 2, 2, 6.7, ""),
        ("Denis Zakaria", "MF", "Monaco", "Ligue 1", 2, 1, 6.8, ""),
        ("Fabian Rieder", "MF", "Rennes", "Ligue 1", 2, 3, 6.6, ""),
        ("Michel Aebischer", "MF", "Bologna", "Serie A", 1, 2, 6.5, ""),
        ("Breel Embolo", "FW", "Monaco", "Ligue 1", 8, 3, 6.9, ""),
        ("Zeki Amdouni", "FW", "Burnley", "Premier League", 6, 3, 6.8, ""),
        ("Ruben Vargas", "FW", "Augsburg", "Bundesliga", 4, 2, 6.7, ""),
        ("Noah Okafor", "FW", "AC Milan", "Serie A", 4, 2, 6.7, ""),
    ],

    # === GROUP C ===
    "Brazil": [
        ("Alisson", "GK", "Liverpool", "Premier League", 0, 0, 7.3, ""),
        ("Ederson", "GK", "Manchester City", "Premier League", 0, 0, 7.1, ""),
        ("Bento", "GK", "Athletico Paranaense", "Brazilian Serie A", 0, 0, 6.5, ""),
        ("Marquinhos", "DF", "PSG", "Ligue 1", 1, 0, 7.0, ""),
        ("Gabriel Magalhães", "DF", "Arsenal", "Premier League", 2, 0, 7.2, ""),
        ("Gleison Bremer", "DF", "Juventus", "Serie A", 1, 0, 7.0, ""),
        ("Murillo", "DF", "Nottingham Forest", "Premier League", 0, 0, 6.8, ""),
        ("Danilo", "DF", "Juventus", "Serie A", 0, 2, 6.7, ""),
        ("Alex Sandro", "DF", "Flamengo", "Brazilian Serie A", 0, 1, 6.6, ""),
        ("Vanderson", "DF", "Monaco", "Ligue 1", 0, 3, 6.8, ""),
        ("Casemiro", "MF", "Manchester United", "Premier League", 2, 2, 6.9, ""),
        ("Bruno Guimarães", "MF", "Newcastle", "Premier League", 3, 5, 7.2, ""),
        ("João Gomes", "MF", "Wolves", "Premier League", 2, 2, 6.8, ""),
        ("André", "MF", "Liverpool", "Premier League", 1, 2, 6.7, ""),
        ("Lucas Paquetá", "MF", "West Ham", "Premier League", 4, 5, 7.1, ""),
        ("Vinícius Júnior", "FW", "Real Madrid", "La Liga", 16, 6, 7.5, ""),
        ("Neymar", "FW", "Santos", "Brazilian Serie A", 18, 9, 7.6, "Injury doubt"),
        ("Gabriel Martinelli", "FW", "Arsenal", "Premier League", 10, 5, 7.1, ""),
        ("Raphinha", "FW", "Barcelona", "La Liga", 12, 7, 7.6, ""),
        ("Endrick", "FW", "Real Madrid", "La Liga", 6, 2, 6.9, ""),
        ("Savinho", "FW", "Manchester City", "Premier League", 5, 4, 7.0, ""),
    ],
    "Morocco": [
        ("Yassine Bounou", "GK", "Al Hilal", "Saudi Pro League", 0, 0, 7.0, ""),
        ("Munir Mohand", "GK", "Al Wehda", "Saudi Pro League", 0, 0, 6.2, ""),
        ("Achraf Hakimi", "DF", "PSG", "Ligue 1", 5, 7, 7.4, "Captain"),
        ("Noussair Mazraoui", "DF", "Manchester United", "Premier League", 1, 3, 7.0, ""),
        ("Romain Saïss", "DF", "Al Sadd", "Qatar Stars League", 1, 0, 6.6, ""),
        ("Nayef Aguerd", "DF", "West Ham", "Premier League", 1, 0, 6.8, ""),
        ("Yahya Attiat-Allah", "DF", "Al Ahly", "—", 0, 1, 6.4, ""),
        ("Chadi Riad", "DF", "Crystal Palace", "Premier League", 0, 0, 6.5, ""),
        ("Sofyan Amrabat", "MF", "Manchester United", "Premier League", 1, 2, 6.7, ""),
        ("Azzedine Ounahi", "MF", "Marseille", "Ligue 1", 2, 3, 6.8, ""),
        ("Bilal El Khannouss", "MF", "Leicester City", "Premier League", 2, 3, 6.7, ""),
        ("Amir Richardson", "MF", "Reims", "Ligue 1", 1, 1, 6.5, ""),
        ("Brahim Díaz", "MF", "Real Madrid", "La Liga", 9, 5, 7.2, ""),
        ("Ismaïl Saibari", "MF", "PSV", "Eredivisie", 3, 3, 6.7, ""),
        ("Youssef En-Nesyri", "FW", "Fenerbahçe", "Turkish Super Lig", 8, 1, 6.8, ""),
        ("Eliesse Ben Seghir", "FW", "Monaco", "Ligue 1", 5, 3, 6.8, ""),
        ("Ayoub El Kaabi", "FW", "Olympiacos", "Greek Super League", 9, 1, 6.9, ""),
    ],
    "Haiti": [
        ("Johnny Placide", "GK", "—", "—", 0, 0, 5.8, ""),
        ("Carlens Arcus", "DF", "Vitesse", "Eredivisie", 0, 0, 6.0, ""),
        ("Ricardo Adé", "DF", "LDU Quito", "—", 0, 0, 6.1, ""),
        ("Alex Christian", "DF", "—", "—", 0, 0, 5.8, ""),
        ("Djimy Alexis", "DF", "—", "—", 0, 0, 5.7, ""),
        ("Jean-Ricner Bellegarde", "MF", "Wolves", "Premier League", 2, 2, 6.7, ""),
        ("Bryan Alceus", "MF", "—", "—", 1, 1, 6.0, ""),
        ("Leverton Pierre", "MF", "—", "—", 1, 0, 6.0, ""),
        ("Carl Fred Sainté", "MF", "—", "—", 0, 1, 5.9, ""),
        ("Duckens Nazon", "FW", "—", "—", 4, 1, 6.3, "All-time top scorer"),
        ("Frantzdy Pierrot", "FW", "Maccabi Haifa", "—", 5, 1, 6.4, ""),
        ("Wilson Isidor", "FW", "Sunderland", "Championship", 5, 2, 6.6, ""),
        ("Mondy Prunier", "FW", "—", "—", 2, 0, 6.0, ""),
    ],
    "Scotland": [
        ("Craig Gordon", "GK", "Hearts", "Scottish Premiership", 0, 0, 6.5, "43yo oldest"),
        ("Angus Gunn", "GK", "Norwich", "Championship", 0, 0, 6.4, ""),
        ("Zander Clark", "GK", "Hearts", "Scottish Premiership", 0, 0, 6.0, ""),
        ("Andrew Robertson", "DF", "Liverpool", "Premier League", 1, 5, 7.0, "Captain"),
        ("Kieran Tierney", "DF", "Celtic", "Scottish Premiership", 1, 3, 6.9, ""),
        ("Jack Hendry", "DF", "Al Ettifaq", "Saudi Pro League", 1, 0, 6.5, ""),
        ("Ryan Porteous", "DF", "Watford", "Championship", 0, 0, 6.4, ""),
        ("Scott McKenna", "DF", "Nottingham Forest", "Premier League", 0, 0, 6.4, ""),
        ("Nathan Patterson", "DF", "Everton", "Premier League", 0, 1, 6.5, ""),
        ("Aaron Hickey", "DF", "Brentford", "Premier League", 0, 2, 6.6, ""),
        ("Scott McTominay", "MF", "Napoli", "Serie A", 7, 2, 7.1, ""),
        ("John McGinn", "MF", "Aston Villa", "Premier League", 4, 4, 6.9, ""),
        ("Callum McGregor", "MF", "Celtic", "Scottish Premiership", 3, 3, 6.8, ""),
        ("Stuart Armstrong", "MF", "Southampton", "Championship", 2, 2, 6.5, ""),
        ("Tyler Fletcher", "MF", "Manchester United U21", "—", 0, 0, 6.0, "Replaced injured Gilmour"),
        ("Lyndon Dykes", "FW", "QPR", "Championship", 5, 1, 6.5, ""),
        ("Ché Adams", "FW", "Southampton", "Championship", 6, 2, 6.6, ""),
        ("Lawrence Shankland", "FW", "Hearts", "Scottish Premiership", 8, 1, 6.7, ""),
    ],

    # === GROUP D ===
    "United States": [
        ("Matt Turner", "GK", "Nottingham Forest", "Premier League", 0, 0, 6.8, ""),
        ("Ethan Horvath", "GK", "Cardiff City", "Championship", 0, 0, 6.3, ""),
        ("Gaga Slonina", "GK", "Chelsea", "Premier League", 0, 0, 6.2, ""),
        ("Antonee Robinson", "DF", "Fulham", "Premier League", 1, 5, 7.1, ""),
        ("Sergiño Dest", "DF", "PSV", "Eredivisie", 1, 4, 7.0, ""),
        ("Chris Richards", "DF", "Crystal Palace", "Premier League", 1, 0, 6.8, ""),
        ("Tim Ream", "DF", "Fulham", "Premier League", 0, 0, 6.5, ""),
        ("Cameron Carter-Vickers", "DF", "Celtic", "Scottish Premiership", 0, 0, 6.6, ""),
        ("Joe Scally", "DF", "Borussia Mönchengladbach", "Bundesliga", 0, 1, 6.5, ""),
        ("Marlon Fossey", "DF", "Standard Liège", "Belgian Pro League", 0, 1, 6.4, ""),
        ("Weston McKennie", "MF", "Juventus", "Serie A", 5, 5, 7.1, ""),
        ("Tyler Adams", "MF", "Bournemouth", "Premier League", 1, 2, 6.9, ""),
        ("Yunus Musah", "MF", "AC Milan", "Serie A", 2, 2, 6.8, ""),
        ("Gio Reyna", "MF", "Borussia Dortmund", "Bundesliga", 3, 4, 6.9, ""),
        ("Luca de la Torre", "MF", "Celta Vigo", "La Liga", 1, 1, 6.5, ""),
        ("Malik Tillman", "MF", "PSV", "Eredivisie", 4, 3, 6.8, ""),
        ("Christian Pulisic", "FW", "AC Milan", "Serie A", 14, 8, 7.4, "Captain"),
        ("Folarin Balogun", "FW", "Monaco", "Ligue 1", 12, 3, 7.1, ""),
        ("Tim Weah", "FW", "Juventus", "Serie A", 4, 3, 6.8, ""),
        ("Ricardo Pepi", "FW", "PSV", "Eredivisie", 7, 2, 6.9, ""),
        ("Alejandro Zendejas", "FW", "América", "Liga MX", 5, 4, 6.8, "Replaced injured Cardoso"),
    ],
    "Paraguay": [
        ("Carlos Coronel", "GK", "New York Red Bulls", "MLS", 0, 0, 6.2, ""),
        ("Gustavo Gómez", "DF", "Palmeiras", "Brazilian Serie A", 1, 0, 6.8, "Captain"),
        ("Fabián Balbuena", "DF", "Dinamo Moscow", "Russian PL", 1, 0, 6.5, ""),
        ("Júnior Alonso", "DF", "Krasnodar", "Russian PL", 0, 0, 6.5, ""),
        ("Omar Alderete", "DF", "Getafe", "La Liga", 0, 0, 6.4, ""),
        ("Miguel Almirón", "MF", "Atlanta United", "MLS", 5, 4, 6.9, ""),
        ("Mathías Villasanti", "MF", "Grêmio", "Brazilian Serie A", 2, 2, 6.7, ""),
        ("Richard Sánchez", "MF", "América", "Liga MX", 3, 2, 6.6, ""),
        ("Diego Gómez", "MF", "Inter Miami", "MLS", 2, 3, 6.7, ""),
        ("Ramón Sosa", "MF", "Nottingham Forest", "Premier League", 3, 2, 6.6, ""),
        ("Julio Enciso", "FW", "Brighton", "Premier League", 6, 3, 6.9, "Injury doubt"),
        ("Gabriel Ávalos", "FW", "Independiente", "Argentine Primera", 5, 1, 6.5, ""),
        ("Alex Arce", "FW", "LDU Quito", "—", 4, 1, 6.4, ""),
    ],
    "Australia": [
        ("Mathew Ryan", "GK", "AZ Alkmaar", "Eredivisie", 0, 0, 6.7, "Captain"),
        ("Joe Gauci", "GK", "Aston Villa", "Premier League", 0, 0, 6.2, ""),
        ("Harry Souttar", "DF", "Leicester City", "Championship", 1, 0, 6.7, ""),
        ("Kye Rowles", "DF", "Hearts", "Scottish Premiership", 0, 0, 6.3, ""),
        ("Cameron Burgess", "DF", "Ipswich Town", "Championship", 0, 0, 6.3, ""),
        ("Alessandro Circati", "DF", "Parma", "Serie A", 0, 0, 6.4, ""),
        ("Connor Metcalfe", "MF", "St. Pauli", "Bundesliga", 2, 1, 6.5, ""),
        ("Jackson Irvine", "MF", "St. Pauli", "Bundesliga", 3, 2, 6.7, ""),
        ("Riley McGree", "MF", "Middlesbrough", "Championship", 2, 2, 6.5, ""),
        ("Ajdin Hrustic", "MF", "Hellas Verona", "Serie A", 1, 2, 6.4, ""),
        ("Cristian Volpato", "MF", "Sassuolo", "Serie A", 2, 2, 6.5, "Switched from Italy"),
        ("Nestory Irankunda", "FW", "Watford", "Championship", 4, 2, 6.6, ""),
        ("Kusini Yengi", "FW", "Portsmouth", "Championship", 3, 1, 6.3, ""),
        ("Brandon Borrello", "FW", "Western Sydney", "A-League", 3, 1, 6.2, ""),
    ],
    "Turkey": [
        ("Mert Günok", "GK", "Beşiktaş", "Turkish Super Lig", 0, 0, 6.5, ""),
        ("Uğurcan Çakır", "GK", "Trabzonspor", "Turkish Super Lig", 0, 0, 6.4, ""),
        ("Çağlar Söyüncü", "DF", "Fenerbahçe", "Turkish Super Lig", 1, 0, 6.7, ""),
        ("Merih Demiral", "DF", "Al Ahli", "Saudi Pro League", 1, 0, 6.6, ""),
        ("Ferdi Kadıoğlu", "DF", "Brighton", "Premier League", 0, 3, 6.8, ""),
        ("Zeki Çelik", "DF", "Roma", "Serie A", 0, 1, 6.5, ""),
        ("Abdülkerim Bardakcı", "DF", "Galatasaray", "Turkish Super Lig", 0, 0, 6.5, ""),
        ("Hakan Çalhanoğlu", "MF", "Inter Milan", "Serie A", 7, 6, 7.2, "Captain"),
        ("Orkun Kökçü", "MF", "Benfica", "Liga Portugal", 4, 4, 7.0, ""),
        ("Salih Özcan", "MF", "Borussia Dortmund", "Bundesliga", 1, 2, 6.6, ""),
        ("İsmail Yüksek", "MF", "Fenerbahçe", "Turkish Super Lig", 1, 1, 6.5, ""),
        ("Arda Güler", "MF", "Real Madrid", "La Liga", 6, 7, 7.1, ""),
        ("Kenan Yıldız", "FW", "Juventus", "Serie A", 8, 4, 7.0, ""),
        ("Kerem Aktürkoğlu", "FW", "Galatasaray", "Turkish Super Lig", 7, 5, 7.0, ""),
        ("Barış Alper Yılmaz", "FW", "Galatasaray", "Turkish Super Lig", 5, 3, 6.8, ""),
    ],

    # === GROUP E ===
    "Germany": [
        ("Manuel Neuer", "GK", "Bayern Munich", "Bundesliga", 0, 0, 7.1, "Returned at 40"),
        ("Alexander Nübel", "GK", "VfB Stuttgart", "Bundesliga", 0, 0, 6.7, ""),
        ("Oliver Baumann", "GK", "Hoffenheim", "Bundesliga", 0, 0, 6.5, ""),
        ("Joshua Kimmich", "DF", "Bayern Munich", "Bundesliga", 3, 8, 7.3, "Captain"),
        ("Antonio Rüdiger", "DF", "Real Madrid", "La Liga", 1, 0, 7.1, ""),
        ("Nico Schlotterbeck", "DF", "Borussia Dortmund", "Bundesliga", 1, 0, 7.0, ""),
        ("Jonathan Tah", "DF", "Bayer Leverkusen", "Bundesliga", 0, 0, 6.8, ""),
        ("Benjamin Henrichs", "DF", "RB Leipzig", "Bundesliga", 0, 2, 6.7, ""),
        ("David Raum", "DF", "RB Leipzig", "Bundesliga", 0, 3, 6.8, ""),
        ("Waldemar Anton", "DF", "Borussia Dortmund", "Bundesliga", 0, 0, 6.6, ""),
        ("Jamal Musiala", "MF", "Bayern Munich", "Bundesliga", 14, 8, 7.6, ""),
        ("Florian Wirtz", "MF", "Liverpool", "Premier League", 9, 11, 7.5, ""),
        ("İlkay Gündoğan", "MF", "Barcelona", "La Liga", 4, 5, 7.0, ""),
        ("Leon Goretzka", "MF", "Bayern Munich", "Bundesliga", 4, 3, 7.0, ""),
        ("Assan Ouédraogo", "MF", "RB Leipzig", "Bundesliga", 2, 2, 6.6, "Replaced injured Karl"),
        ("Kai Havertz", "FW", "Arsenal", "Premier League", 10, 5, 7.1, ""),
        ("Leroy Sané", "FW", "Bayern Munich", "Bundesliga", 7, 6, 7.2, ""),
        ("Niclas Füllkrug", "FW", "Borussia Dortmund", "Bundesliga", 8, 2, 6.9, ""),
        ("Maximilian Beier", "FW", "Borussia Dortmund", "Bundesliga", 5, 2, 6.7, ""),
        ("Karim Adeyemi", "FW", "Borussia Dortmund", "Bundesliga", 6, 3, 6.9, ""),
    ],
    "Curacao": [
        ("Eloy Room", "GK", "Vitesse", "Eredivisie", 0, 0, 6.0, ""),
        ("Riechedly Bazoer", "DF", "AZ Alkmaar", "Eredivisie", 1, 0, 6.4, ""),
        ("Cuco Martina", "DF", "—", "—", 0, 0, 5.8, ""),
        ("Jurich Carolina", "DF", "Miedź Legnica", "—", 0, 0, 5.7, ""),
        ("Leandro Bacuna", "MF", "FC Groningen", "Eredivisie", 2, 2, 6.3, "Captain"),
        ("Vurnon Anita", "MF", "—", "—", 0, 1, 5.9, ""),
        ("Juninho Bacuna", "MF", "Birmingham City", "Championship", 2, 2, 6.4, ""),
        ("Kenji Gorré", "MF", "—", "—", 1, 1, 6.0, ""),
        ("Tahith Chong", "FW", "Sheffield United", "Championship", 3, 2, 6.5, ""),
        ("Rangelo Janga", "FW", "—", "—", 2, 0, 6.0, ""),
        ("Anthony van den Hurk", "FW", "—", "—", 2, 1, 6.0, ""),
    ],
    "Ivory Coast": [
        ("Yahia Fofana", "GK", "Angers", "Ligue 1", 0, 0, 6.3, ""),
        ("Evan Ndicka", "DF", "Roma", "Serie A", 1, 0, 6.9, ""),
        ("Ousmane Diomande", "DF", "Sporting CP", "Liga Portugal", 0, 0, 6.7, ""),
        ("Willy Boly", "DF", "Nottingham Forest", "Premier League", 0, 0, 6.4, ""),
        ("Ghislain Konan", "DF", "Al Nassr", "Saudi Pro League", 0, 1, 6.3, ""),
        ("Franck Kessié", "MF", "Al Ahli", "Saudi Pro League", 4, 2, 6.9, "Captain"),
        ("Seko Fofana", "MF", "Al Nassr", "Saudi Pro League", 3, 2, 6.8, ""),
        ("Ibrahim Sangaré", "MF", "Nottingham Forest", "Premier League", 1, 2, 6.7, ""),
        ("Amad Diallo", "MF", "Manchester United", "Premier League", 5, 4, 7.0, ""),
        ("Simon Adingra", "FW", "Brighton", "Premier League", 5, 4, 6.9, ""),
        ("Nicolas Pépé", "FW", "Villarreal", "La Liga", 6, 3, 6.8, ""),
        ("Sébastien Haller", "FW", "Borussia Dortmund", "Bundesliga", 8, 2, 6.8, ""),
        ("Jean-Philippe Krasso", "FW", "Saint-Étienne", "Ligue 1", 4, 1, 6.5, ""),
    ],
    "Ecuador": [
        ("Hernán Galíndez", "GK", "Huracán", "Argentine Primera", 0, 0, 6.2, ""),
        ("Piero Hincapié", "DF", "Arsenal", "Premier League", 1, 1, 7.0, ""),
        ("Willian Pacho", "DF", "PSG", "Ligue 1", 0, 0, 6.9, ""),
        ("Félix Torres", "DF", "Santos Laguna", "Liga MX", 1, 0, 6.4, ""),
        ("Angelo Preciado", "DF", "Sparta Praha", "Czech First League", 0, 1, 6.3, ""),
        ("Moisés Caicedo", "MF", "Chelsea", "Premier League", 2, 3, 7.1, ""),
        ("Carlos Gruezo", "MF", "San Jose Earthquakes", "MLS", 1, 1, 6.3, ""),
        ("Alan Franco", "MF", "Atlético Mineiro", "Brazilian Serie A", 1, 1, 6.3, ""),
        ("Jeremy Sarmiento", "MF", "Ipswich", "Championship", 2, 2, 6.4, ""),
        ("Kendry Páez", "MF", "Chelsea", "Premier League", 4, 5, 6.8, ""),
        ("Enner Valencia", "FW", "Internacional", "Brazilian Serie A", 10, 3, 6.8, "Captain"),
        ("Leonardo Campana", "FW", "Inter Miami", "MLS", 5, 1, 6.4, ""),
        ("Kevin Rodríguez", "FW", "Union SG", "Belgian Pro League", 3, 1, 6.3, ""),
    ],

    # === GROUP F ===
    "Netherlands": [
        ("Bart Verbruggen", "GK", "Brighton", "Premier League", 0, 0, 7.0, ""),
        ("Mark Flekken", "GK", "Brentford", "Premier League", 0, 0, 6.7, ""),
        ("Virgil van Dijk", "DF", "Liverpool", "Premier League", 2, 1, 7.3, "Captain"),
        ("Nathan Aké", "DF", "Manchester City", "Premier League", 1, 0, 6.9, ""),
        ("Micky van de Ven", "DF", "Tottenham", "Premier League", 1, 0, 7.0, ""),
        ("Denzel Dumfries", "DF", "Inter Milan", "Serie A", 2, 3, 7.0, ""),
        ("Lutsharel Geertruida", "DF", "RB Leipzig", "Bundesliga", 1, 2, 6.8, ""),
        ("Quilindschy Hartman", "DF", "Feyenoord", "Eredivisie", 0, 2, 6.6, ""),
        ("Stefan de Vrij", "DF", "Inter Milan", "Serie A", 0, 0, 6.7, ""),
        ("Frenkie de Jong", "MF", "Barcelona", "La Liga", 3, 6, 7.3, ""),
        ("Ryan Gravenberch", "MF", "Liverpool", "Premier League", 2, 3, 7.0, ""),
        ("Teun Koopmeiners", "MF", "Juventus", "Serie A", 4, 4, 7.0, ""),
        ("Tijjani Reijnders", "MF", "AC Milan", "Serie A", 3, 3, 6.9, ""),
        ("Mats Wieffer", "MF", "Brighton", "Premier League", 1, 2, 6.7, ""),
        ("Cody Gakpo", "FW", "Liverpool", "Premier League", 9, 5, 7.0, ""),
        ("Memphis Depay", "FW", "Corinthians", "Brazilian Serie A", 7, 4, 6.8, ""),
        ("Donyell Malen", "FW", "Aston Villa", "Premier League", 18, 3, 7.0, ""),
        ("Brian Brobbey", "FW", "Ajax", "Eredivisie", 8, 2, 6.8, ""),
    ],
    "Japan": [
        ("Zion Suzuki", "GK", "Sint-Truiden", "Belgian Pro League", 0, 0, 6.3, ""),
        ("Keisuke Osako", "GK", "Sanfrecce Hiroshima", "J1 League", 0, 0, 6.2, ""),
        ("Takehiro Tomiyasu", "DF", "Arsenal", "Premier League", 1, 2, 7.0, ""),
        ("Hiroki Ito", "DF", "Bayern Munich", "Bundesliga", 1, 1, 6.9, ""),
        ("Ko Itakura", "DF", "Borussia Mönchengladbach", "Bundesliga", 1, 0, 6.7, ""),
        ("Yukinari Sugawara", "DF", "Southampton", "Premier League", 0, 2, 6.6, ""),
        ("Shogo Taniguchi", "DF", "Al Rayyan", "Qatar Stars League", 0, 0, 6.3, ""),
        ("Wataru Endo", "MF", "Liverpool", "Premier League", 2, 2, 7.0, "Captain"),
        ("Takefusa Kubo", "MF", "Real Sociedad", "La Liga", 5, 6, 7.1, ""),
        ("Daichi Kamada", "MF", "Crystal Palace", "Premier League", 3, 3, 6.8, ""),
        ("Ritsu Doan", "MF", "Freiburg", "Bundesliga", 4, 3, 6.9, ""),
        ("Hidemasa Morita", "MF", "Sporting CP", "Liga Portugal", 2, 2, 6.7, ""),
        ("Reo Hatate", "MF", "Celtic", "Scottish Premiership", 3, 4, 6.8, ""),
        ("Daizen Maeda", "FW", "Celtic", "Scottish Premiership", 12, 4, 7.0, ""),
        ("Kyogo Furuhashi", "FW", "Celtic", "Scottish Premiership", 10, 2, 6.9, ""),
        ("Ayase Ueda", "FW", "Feyenoord", "Eredivisie", 6, 2, 6.7, ""),
    ],
    "Sweden": [
        ("Robin Olsen", "GK", "Aston Villa", "Premier League", 0, 0, 6.3, ""),
        ("Victor Lindelöf", "DF", "Manchester United", "Premier League", 0, 0, 6.5, ""),
        ("Isak Hien", "DF", "Atalanta", "Serie A", 0, 0, 6.6, ""),
        ("Ludwig Augustinsson", "DF", "Anderlecht", "Belgian Pro League", 0, 1, 6.3, ""),
        ("Emil Holm", "DF", "Atalanta", "Serie A", 0, 2, 6.5, ""),
        ("Emil Forsberg", "MF", "New York Red Bulls", "MLS", 4, 3, 6.7, ""),
        ("Mattias Svanberg", "MF", "Wolfsburg", "Bundesliga", 2, 2, 6.6, ""),
        ("Jens Cajuste", "MF", "Napoli", "Serie A", 1, 2, 6.5, ""),
        ("Lucas Bergvall", "MF", "Tottenham", "Premier League", 2, 3, 6.7, ""),
        ("Hugo Larsson", "MF", "Eintracht Frankfurt", "Bundesliga", 2, 2, 6.7, ""),
        ("Alexander Isak", "FW", "Newcastle", "Premier League", 19, 5, 7.5, ""),
        ("Viktor Gyökeres", "FW", "Sporting CP", "Liga Portugal", 22, 6, 7.6, ""),
        ("Anthony Elanga", "FW", "Newcastle", "Premier League", 6, 4, 6.9, ""),
        ("Niclas Eliasson", "FW", "AEK Athens", "Greek Super League", 3, 5, 6.5, ""),
    ],
    "Tunisia": [
        ("Bechir Ben Saïd", "GK", "US Monastir", "—", 0, 0, 6.0, ""),
        ("Montassar Talbi", "DF", "Lorient", "Ligue 1", 0, 0, 6.3, ""),
        ("Dylan Bronn", "DF", "Salernitana", "Serie B", 0, 0, 6.1, ""),
        ("Yan Valery", "DF", "Angers", "Ligue 1", 0, 1, 6.2, ""),
        ("Ali Abdi", "DF", "Nice", "Ligue 1", 0, 1, 6.3, ""),
        ("Ellyes Skhiri", "MF", "Eintracht Frankfurt", "Bundesliga", 2, 1, 6.8, ""),
        ("Aïssa Laïdouni", "MF", "Union Berlin", "Bundesliga", 1, 1, 6.5, ""),
        ("Hannibal Mejbri", "MF", "Burnley", "Championship", 2, 3, 6.6, ""),
        ("Anis Ben Slimane", "MF", "Sheffield United", "Championship", 1, 2, 6.4, ""),
        ("Youssef Msakni", "FW", "Al Arabi", "Qatar Stars League", 4, 2, 6.6, "Captain"),
        ("Wahbi Khazri", "FW", "Montpellier", "Ligue 1", 3, 2, 6.4, ""),
        ("Elias Saad", "FW", "St. Pauli", "Bundesliga", 2, 1, 6.3, ""),
    ],

    # === GROUP G ===
    "Belgium": [
        ("Thibaut Courtois", "GK", "Real Madrid", "La Liga", 0, 0, 7.3, ""),
        ("Koen Casteels", "GK", "Al Qadsiah", "Saudi Pro League", 0, 0, 6.5, ""),
        ("Wout Faes", "DF", "Leicester City", "Premier League", 0, 0, 6.5, ""),
        ("Zeno Debast", "DF", "Sporting CP", "Liga Portugal", 1, 0, 6.6, ""),
        ("Arthur Theate", "DF", "Rennes", "Ligue 1", 0, 0, 6.5, ""),
        ("Timothy Castagne", "DF", "Fulham", "Premier League", 0, 1, 6.5, ""),
        ("Maxim De Cuyper", "DF", "Club Brugge", "Belgian Pro League", 1, 2, 6.7, ""),
        ("Kevin De Bruyne", "MF", "Manchester City", "Premier League", 7, 12, 7.4, "Captain"),
        ("Jérémy Doku", "MF", "Manchester City", "Premier League", 5, 8, 7.1, ""),
        ("Amadou Onana", "MF", "Aston Villa", "Premier League", 2, 2, 6.9, ""),
        ("Youri Tielemans", "MF", "Aston Villa", "Premier League", 3, 4, 6.9, ""),
        ("Charles De Ketelaere", "MF", "Atalanta", "Serie A", 5, 5, 7.0, ""),
        ("Orel Mangala", "MF", "Lyon", "Ligue 1", 1, 2, 6.7, ""),
        ("Romelu Lukaku", "FW", "Napoli", "Serie A", 7, 2, 6.9, "Injury limited"),
        ("Leandro Trossard", "FW", "Arsenal", "Premier League", 10, 6, 7.1, ""),
        ("Loïs Openda", "FW", "RB Leipzig", "Bundesliga", 14, 2, 7.1, ""),
        ("Johan Bakayoko", "FW", "PSV", "Eredivisie", 6, 5, 7.0, ""),
    ],
    "Egypt": [
        ("Mohamed El Shenawy", "GK", "Al Ahly", "—", 0, 0, 6.3, ""),
        ("Ahmed Hegazi", "DF", "Al Ittihad", "Saudi Pro League", 0, 0, 6.3, ""),
        ("Mohamed Abdelmonem", "DF", "Nice", "Ligue 1", 0, 0, 6.4, ""),
        ("Mohamed Hany", "DF", "Al Ahly", "—", 0, 1, 6.2, ""),
        ("Hamdi Fathi", "MF", "Al Ahly", "—", 2, 2, 6.4, ""),
        ("Emam Ashour", "MF", "Al Ahly", "—", 3, 2, 6.5, ""),
        ("Marwan Attia", "MF", "Al Ahly", "—", 1, 1, 6.4, ""),
        ("Mohamed Salah", "FW", "Liverpool", "Premier League", 14, 7, 7.3, "Captain"),
        ("Omar Marmoush", "FW", "Manchester City", "Premier League", 16, 5, 7.5, ""),
        ("Trézéguet", "FW", "Trabzonspor", "Turkish Super Lig", 5, 3, 6.8, ""),
        ("Mostafa Mohamed", "FW", "Nantes", "Ligue 1", 7, 2, 6.7, ""),
    ],
    "Iran": [
        ("Alireza Beiranvand", "GK", "Persepolis", "Persian Gulf Pro League", 0, 0, 6.3, ""),
        ("Hossein Kanaani", "DF", "Persepolis", "Persian Gulf Pro League", 0, 0, 6.2, ""),
        ("Shoja Khalilzadeh", "DF", "Tractor", "Persian Gulf Pro League", 0, 0, 6.2, ""),
        ("Ehsan Hajsafi", "DF", "AEK Athens", "Greek Super League", 0, 1, 6.3, ""),
        ("Saeid Ezatolahi", "MF", "Shabab Al Ahli", "UAE League", 1, 1, 6.2, ""),
        ("Saman Ghoddos", "MF", "Brentford", "Premier League", 1, 2, 6.5, ""),
        ("Alireza Jahanbakhsh", "MF", "Feyenoord", "Eredivisie", 2, 3, 6.5, ""),
        ("Mehdi Taremi", "FW", "Olympiacos", "Greek Super League", 9, 4, 6.9, ""),
        ("Sardar Azmoun", "FW", "Roma", "Serie A", 8, 2, 6.8, ""),
        ("Mehdi Ghayedi", "FW", "Al Ittihad Kalba", "UAE League", 4, 2, 6.4, ""),
        ("Shahriyar Moghanlou", "FW", "Sepahan", "Persian Gulf Pro League", 5, 1, 6.3, ""),
    ],
    "New Zealand": [
        ("Max Crocombe", "GK", "Burton Albion", "League One", 0, 0, 5.9, ""),
        ("Michael Boxall", "DF", "Minnesota United", "MLS", 0, 0, 6.1, ""),
        ("Nando Pijnaker", "DF", "Sligo Rovers", "League of Ireland", 0, 0, 5.8, ""),
        ("Liberato Cacace", "DF", "Empoli", "Serie A", 0, 1, 6.3, ""),
        ("Tim Payne", "DF", "Wellington Phoenix", "A-League", 0, 0, 5.9, ""),
        ("Joe Bell", "MF", "Viking FK", "Norwegian Eliteserien", 1, 1, 6.1, ""),
        ("Sarpreet Singh", "MF", "Hansa Rostock", "2. Bundesliga", 2, 2, 6.3, ""),
        ("Marko Stamenic", "MF", "Nottingham Forest", "Premier League", 0, 1, 6.3, ""),
        ("Chris Wood", "FW", "Nottingham Forest", "Premier League", 9, 2, 6.9, "Captain"),
        ("Ben Waine", "FW", "Plymouth Argyle", "League One", 3, 1, 6.2, ""),
        ("Callum McCowatt", "FW", "Silkeborg", "Danish Superliga", 2, 1, 6.1, ""),
    ],

    # === GROUP H ===
    "Spain": [
        ("Unai Simón", "GK", "Athletic Bilbao", "La Liga", 0, 0, 7.1, ""),
        ("David Raya", "GK", "Arsenal", "Premier League", 0, 0, 7.3, ""),
        ("Álex Remiro", "GK", "Real Sociedad", "La Liga", 0, 0, 6.7, ""),
        ("Rodri", "MF", "Manchester City", "Premier League", 4, 5, 7.5, "Captain (acting)"),
        ("Pedri", "MF", "Barcelona", "La Liga", 5, 9, 7.6, ""),
        ("Gavi", "MF", "Barcelona", "La Liga", 3, 5, 7.2, ""),
        ("Dani Olmo", "MF", "Barcelona", "La Liga", 6, 5, 7.2, ""),
        ("Fabián Ruiz", "MF", "PSG", "Ligue 1", 3, 4, 7.0, ""),
        ("Martín Zubimendi", "MF", "Real Sociedad", "La Liga", 1, 2, 7.0, ""),
        ("Álex Baena", "MF", "Villarreal", "La Liga", 4, 7, 7.1, ""),
        ("Pau Cubarsí", "DF", "Barcelona", "La Liga", 1, 1, 7.0, ""),
        ("Robin Le Normand", "DF", "Atlético Madrid", "La Liga", 0, 0, 6.8, ""),
        ("Alejandro Balde", "DF", "Barcelona", "La Liga", 0, 3, 6.9, ""),
        ("Dani Vivian", "DF", "Athletic Bilbao", "La Liga", 0, 0, 6.8, ""),
        ("Óscar Mingueza", "DF", "Celta Vigo", "La Liga", 0, 2, 6.7, ""),
        ("Lamine Yamal", "FW", "Barcelona", "La Liga", 18, 22, 8.0, ""),
        ("Nico Williams", "FW", "Athletic Bilbao", "La Liga", 10, 8, 7.3, ""),
        ("Ferran Torres", "FW", "Barcelona", "La Liga", 16, 2, 7.3, ""),
        ("Álvaro Morata", "FW", "Atlético Madrid", "La Liga", 8, 2, 6.9, "Captain"),
        ("Mikel Oyarzabal", "FW", "Real Sociedad", "La Liga", 7, 4, 7.0, ""),
    ],
    "Cape Verde": [
        ("Vozinha", "GK", "—", "—", 0, 0, 5.5, ""),
        ("Stopira", "DF", "—", "—", 0, 0, 5.6, ""),
        ("Logan Costa", "DF", "Villarreal", "La Liga", 1, 0, 6.8, ""),
        ("Dylan Tavares", "DF", "—", "—", 0, 0, 5.7, ""),
        ("Jamiro Monteiro", "MF", "San Jose Earthquakes", "MLS", 2, 3, 6.4, ""),
        ("Kenny Rocha Santos", "MF", "—", "—", 1, 1, 5.9, ""),
        ("Leandro Andrade", "MF", "—", "—", 1, 0, 5.9, ""),
        ("Ryan Mendes", "FW", "—", "—", 3, 1, 6.0, "Captain"),
        ("Garry Rodrigues", "FW", "—", "—", 2, 1, 5.9, ""),
        ("Bebé", "FW", "Rayo Vallecano", "La Liga", 2, 1, 6.2, ""),
        ("Lisandro Semedo", "FW", "—", "—", 1, 0, 5.8, ""),
    ],
    "Saudi Arabia": [
        ("Mohammed Al Owais", "GK", "Al Hilal", "Saudi Pro League", 0, 0, 6.2, ""),
        ("Ali Al Bulayhi", "DF", "Al Hilal", "Saudi Pro League", 0, 0, 6.1, ""),
        ("Hassan Tambakti", "DF", "Al Hilal", "Saudi Pro League", 0, 0, 6.2, ""),
        ("Saud Abdulhamid", "DF", "Roma", "Serie A", 0, 1, 6.3, ""),
        ("Yasser Al Shahrani", "DF", "Al Hilal", "Saudi Pro League", 0, 0, 6.1, ""),
        ("Salem Al Dawsari", "MF", "Al Hilal", "Saudi Pro League", 5, 3, 6.6, "Captain"),
        ("Mohamed Kanno", "MF", "Al Hilal", "Saudi Pro League", 2, 1, 6.4, ""),
        ("Abdulelah Al Malki", "MF", "Al Hilal", "Saudi Pro League", 1, 1, 6.3, ""),
        ("Feras Al Brikan", "FW", "Al Ahli", "Saudi Pro League", 6, 2, 6.5, ""),
        ("Saleh Al Shehri", "FW", "Al Hilal", "Saudi Pro League", 4, 1, 6.4, ""),
        ("Abdullah Radif", "FW", "Al Hilal", "Saudi Pro League", 3, 1, 6.3, ""),
    ],
    "Uruguay": [
        ("Sergio Rochet", "GK", "Internacional", "Brazilian Serie A", 0, 0, 6.6, ""),
        ("Ronald Araújo", "DF", "Barcelona", "La Liga", 2, 1, 7.1, ""),
        ("José María Giménez", "DF", "Atlético Madrid", "La Liga", 1, 0, 7.0, "Injury doubt"),
        ("Sebastián Cáceres", "DF", "América", "Liga MX", 0, 0, 6.5, ""),
        ("Mathías Olivera", "DF", "Napoli", "Serie A", 0, 1, 6.6, ""),
        ("Nahitan Nández", "DF", "Cagliari", "Serie A", 0, 2, 6.5, ""),
        ("Federico Valverde", "MF", "Real Madrid", "La Liga", 6, 8, 7.5, "Captain"),
        ("Manuel Ugarte", "MF", "Manchester United", "Premier League", 2, 3, 7.0, ""),
        ("Rodrigo Bentancur", "MF", "Tottenham", "Premier League", 2, 2, 6.9, ""),
        ("Giorgian de Arrascaeta", "MF", "Flamengo", "Brazilian Serie A", 5, 6, 7.0, "Injury doubt"),
        ("Facundo Pellistri", "MF", "Manchester United", "Premier League", 1, 3, 6.5, ""),
        ("Darwin Núñez", "FW", "Liverpool", "Premier League", 9, 3, 6.9, ""),
        ("Federico Viñas", "FW", "León", "Liga MX", 6, 2, 6.6, ""),
        ("Maximiliano Araújo", "FW", "Toluca", "Liga MX", 4, 3, 6.6, ""),
    ],

    # === GROUP I ===
    "France": [
        ("Mike Maignan", "GK", "AC Milan", "Serie A", 0, 0, 7.2, ""),
        ("Lucas Chevalier", "GK", "Lille", "Ligue 1", 0, 0, 6.8, ""),
        ("William Saliba", "DF", "Arsenal", "Premier League", 1, 0, 7.3, ""),
        ("Ibrahima Konaté", "DF", "Liverpool", "Premier League", 1, 0, 7.0, ""),
        ("Dayot Upamecano", "DF", "Bayern Munich", "Bundesliga", 0, 0, 6.9, ""),
        ("Théo Hernandez", "DF", "AC Milan", "Serie A", 2, 4, 7.2, ""),
        ("Jules Koundé", "DF", "Barcelona", "La Liga", 1, 2, 7.0, ""),
        ("Jonathan Clauss", "DF", "Marseille", "Ligue 1", 0, 3, 6.7, ""),
        ("Aurélien Tchouaméni", "MF", "Real Madrid", "La Liga", 2, 2, 7.1, ""),
        ("Eduardo Camavinga", "MF", "Real Madrid", "La Liga", 1, 2, 7.0, ""),
        ("Warren Zaïre-Emery", "MF", "PSG", "Ligue 1", 2, 3, 7.0, ""),
        ("N'Golo Kanté", "MF", "Al Ittihad", "Saudi Pro League", 1, 2, 7.1, ""),
        ("Adrien Rabiot", "MF", "Juventus", "Serie A", 2, 2, 6.8, ""),
        ("Kylian Mbappé", "FW", "Real Madrid", "La Liga", 24, 8, 7.9, "Captain"),
        ("Ousmane Dembélé", "FW", "PSG", "Ligue 1", 11, 12, 7.5, ""),
        ("Bradley Barcola", "FW", "PSG", "Ligue 1", 11, 7, 7.3, ""),
        ("Randal Kolo Muani", "FW", "PSG", "Ligue 1", 8, 4, 7.0, ""),
        ("Marcus Thuram", "FW", "Inter Milan", "Serie A", 9, 3, 7.1, ""),
        ("Jean-Philippe Mateta", "FW", "Crystal Palace", "Premier League", 7, 2, 6.8, "Replaced injured Ekitiké"),
    ],
    "Senegal": [
        ("Édouard Mendy", "GK", "Al Ahli", "Saudi Pro League", 0, 0, 6.6, ""),
        ("Kalidou Koulibaly", "DF", "Al Hilal", "Saudi Pro League", 1, 0, 7.0, "Captain"),
        ("Abdou Diallo", "DF", "RB Leipzig", "Bundesliga", 0, 0, 6.5, ""),
        ("Ismaël Jakobs", "DF", "Monaco", "Ligue 1", 0, 2, 6.5, ""),
        ("Moussa Niakhaté", "DF", "Nottingham Forest", "Premier League", 0, 0, 6.5, ""),
        ("Pape Matar Sarr", "MF", "Tottenham", "Premier League", 2, 2, 6.9, ""),
        ("Lamine Camara", "MF", "Monaco", "Ligue 1", 2, 3, 6.7, ""),
        ("Idrissa Gueye", "MF", "Everton", "Premier League", 1, 1, 6.6, ""),
        ("Pathé Ciss", "MF", "Rayo Vallecano", "La Liga", 1, 1, 6.4, ""),
        ("Sadio Mané", "FW", "Al Nassr", "Saudi Pro League", 13, 6, 7.3, ""),
        ("Nicolas Jackson", "FW", "Chelsea", "Premier League", 12, 4, 7.2, ""),
        ("Ismaïla Sarr", "FW", "Marseille", "Ligue 1", 6, 4, 6.9, ""),
        ("Boulaye Dia", "FW", "Salernitana", "Serie B", 5, 2, 6.5, ""),
    ],
    "Iraq": [
        ("Jalal Hassan", "GK", "Al Zawraa", "Iraq Stars League", 0, 0, 5.5, ""),
        ("Rebin Sulaka", "DF", "—", "—", 0, 0, 5.6, ""),
        ("Ali Adnan", "DF", "—", "—", 0, 1, 5.8, ""),
        ("Zidane Iqbal", "MF", "FC Utrecht", "Eredivisie", 1, 2, 6.4, ""),
        ("Amir Al Ammari", "MF", "—", "—", 1, 1, 5.7, ""),
        ("Ibrahim Bayesh", "MF", "—", "—", 0, 1, 5.7, ""),
        ("Ali Al-Hamadi", "FW", "AFC Wimbledon", "League Two", 1, 1, 6.3, ""),
        ("Aymen Hussein", "FW", "—", "—", 3, 0, 5.9, ""),
        ("Mohanad Ali", "FW", "—", "—", 2, 0, 5.8, ""),
    ],
    "Norway": [
        ("Ørjan Nyland", "GK", "Sevilla", "La Liga", 0, 0, 6.5, ""),
        ("Leo Østigård", "DF", "Rennes", "Ligue 1", 0, 0, 6.4, ""),
        ("Andreas Hanche-Olsen", "DF", "Mainz", "Bundesliga", 0, 0, 6.3, ""),
        ("Julian Ryerson", "DF", "Borussia Dortmund", "Bundesliga", 0, 2, 6.7, ""),
        ("David Møller Wolfe", "DF", "AZ Alkmaar", "Eredivisie", 0, 1, 6.4, ""),
        ("Martin Ødegaard", "MF", "Arsenal", "Premier League", 8, 11, 7.4, "Captain"),
        ("Sander Berge", "MF", "Burnley", "Championship", 2, 2, 6.6, ""),
        ("Oscar Bobb", "MF", "Manchester City", "Premier League", 3, 4, 6.9, ""),
        ("Antonio Nusa", "MF", "RB Leipzig", "Bundesliga", 4, 4, 6.9, ""),
        ("Kristian Thorstvedt", "MF", "Sassuolo", "Serie A", 2, 2, 6.5, ""),
        ("Erling Haaland", "FW", "Manchester City", "Premier League", 28, 4, 7.8, ""),
        ("Alexander Sørloth", "FW", "Atlético Madrid", "La Liga", 10, 3, 7.0, ""),
        ("Jørgen Strand Larsen", "FW", "Wolves", "Premier League", 6, 2, 6.7, ""),
    ],

    # === GROUP J ===
    "Argentina": [
        ("Emiliano Martínez", "GK", "Aston Villa", "Premier League", 0, 0, 7.3, ""),
        ("Gerónimo Rulli", "GK", "Ajax", "Eredivisie", 0, 0, 6.5, ""),
        ("Cristian Romero", "DF", "Tottenham", "Premier League", 1, 0, 7.1, "Injury doubt"),
        ("Nicolás Otamendi", "DF", "Benfica", "Liga Portugal", 1, 0, 6.7, ""),
        ("Lisandro Martínez", "DF", "Manchester United", "Premier League", 1, 0, 7.0, ""),
        ("Marcos Acuña", "DF", "Sevilla", "La Liga", 0, 2, 6.6, ""),
        ("Nahuel Molina", "DF", "Atlético Madrid", "La Liga", 0, 2, 6.8, "Injury doubt"),
        ("Enzo Fernández", "MF", "Chelsea", "Premier League", 4, 6, 7.2, ""),
        ("Alexis Mac Allister", "MF", "Liverpool", "Premier League", 3, 5, 7.1, ""),
        ("Giovani Lo Celso", "MF", "Tottenham", "Premier League", 2, 4, 6.9, ""),
        ("Exequiel Palacios", "MF", "Bayer Leverkusen", "Bundesliga", 2, 2, 6.8, ""),
        ("Leandro Paredes", "MF", "Roma", "Serie A", 1, 2, 6.7, "Injury doubt"),
        ("Lionel Messi", "FW", "Inter Miami", "MLS", 20, 13, 7.9, "Captain, 6th WC"),
        ("Lautaro Martínez", "FW", "Inter Milan", "Serie A", 17, 6, 7.5, ""),
        ("Julián Álvarez", "FW", "Atlético Madrid", "La Liga", 13, 5, 7.3, ""),
        ("Ángel Di María", "FW", "Benfica", "Liga Portugal", 6, 8, 7.1, "Final tournament"),
        ("Alejandro Garnacho", "FW", "Manchester United", "Premier League", 5, 3, 6.9, ""),
    ],
    "Algeria": [
        ("Anthony Mandrea", "GK", "Caen", "Ligue 2", 0, 0, 5.8, ""),
        ("Ramy Bensebaini", "DF", "Borussia Dortmund", "Bundesliga", 1, 0, 6.6, ""),
        ("Aïssa Mandi", "DF", "Villarreal", "La Liga", 0, 0, 6.4, ""),
        ("Rayan Aït-Nouri", "DF", "Manchester City", "Premier League", 1, 3, 7.0, ""),
        ("Ismaël Bennacer", "MF", "AC Milan", "Serie A", 2, 3, 6.8, ""),
        ("Hicham Boudaoui", "MF", "Nice", "Ligue 1", 2, 2, 6.5, ""),
        ("Rayan Cherki", "MF", "Lyon", "Ligue 1", 5, 6, 7.0, ""),
        ("Houssem Aouar", "MF", "Roma", "Serie A", 3, 3, 6.7, ""),
        ("Riyad Mahrez", "FW", "Al Ahli", "Saudi Pro League", 7, 7, 7.0, "Captain"),
        ("Amine Gouiri", "FW", "Marseille", "Ligue 1", 8, 4, 7.0, ""),
        ("Mohamed Amoura", "FW", "Union SG", "Belgian Pro League", 6, 3, 6.8, ""),
        ("Baghdad Bounedjah", "FW", "Al Sadd", "Qatar Stars League", 5, 1, 6.5, ""),
    ],
    "Austria": [
        ("Alexander Schlager", "GK", "RB Salzburg", "Austrian Bundesliga", 0, 0, 6.2, ""),
        ("David Alaba", "DF", "Real Madrid", "La Liga", 1, 2, 7.0, "Captain"),
        ("Kevin Danso", "DF", "Lens", "Ligue 1", 0, 0, 6.6, ""),
        ("Maximilian Wöber", "DF", "Leeds United", "Championship", 0, 0, 6.3, ""),
        ("Stefan Posch", "DF", "Bologna", "Serie A", 0, 1, 6.5, ""),
        ("Konrad Laimer", "MF", "Bayern Munich", "Bundesliga", 2, 3, 6.9, ""),
        ("Marcel Sabitzer", "MF", "Borussia Dortmund", "Bundesliga", 5, 4, 7.0, ""),
        ("Nicolas Seiwald", "MF", "RB Leipzig", "Bundesliga", 1, 2, 6.7, ""),
        ("Xaver Schlager", "MF", "RB Leipzig", "Bundesliga", 1, 2, 6.6, ""),
        ("Carney Chukwuemeka", "MF", "Chelsea", "Premier League", 2, 2, 6.6, ""),
        ("Marko Arnautović", "FW", "Inter Milan", "Serie A", 5, 2, 6.7, ""),
        ("Michael Gregoritsch", "FW", "Freiburg", "Bundesliga", 4, 2, 6.6, ""),
        ("Junior Adamu", "FW", "Freiburg", "Bundesliga", 3, 1, 6.4, ""),
    ],
    "Jordan": [
        ("Yazid Abu Layla", "GK", "Al Faisaly", "—", 0, 0, 5.3, ""),
        ("Abdallah Nasib", "DF", "Al Faisaly", "—", 0, 0, 5.4, ""),
        ("Ehsan Haddad", "DF", "Al Faisaly", "—", 0, 0, 5.3, ""),
        ("Noor Al Rawabdeh", "MF", "Al Faisaly", "—", 1, 1, 5.5, ""),
        ("Musa Al Taamari", "FW", "Montpellier", "Ligue 1", 4, 2, 6.4, ""),
        ("Yazan Al-Naimat", "FW", "Al Ahli", "Qatar Stars League", 3, 1, 6.0, ""),
        ("Ali Olwan", "FW", "Al Shamal", "Qatar Stars League", 2, 1, 5.8, ""),
    ],

    # === GROUP K ===
    "Portugal": [
        ("Diogo Costa", "GK", "Porto", "Liga Portugal", 0, 0, 7.2, ""),
        ("Rui Patrício", "GK", "Roma", "Serie A", 0, 0, 6.5, ""),
        ("Rúben Dias", "DF", "Manchester City", "Premier League", 2, 1, 7.1, ""),
        ("Gonçalo Inácio", "DF", "Sporting CP", "Liga Portugal", 1, 0, 6.9, ""),
        ("António Silva", "DF", "Benfica", "Liga Portugal", 0, 0, 6.8, ""),
        ("Nuno Mendes", "DF", "PSG", "Ligue 1", 0, 3, 7.0, ""),
        ("João Cancelo", "DF", "Barcelona", "La Liga", 1, 4, 7.0, ""),
        ("Diogo Dalot", "DF", "Manchester United", "Premier League", 0, 2, 6.7, ""),
        ("Bruno Fernandes", "MF", "Manchester United", "Premier League", 8, 10, 7.4, ""),
        ("Bernardo Silva", "MF", "Manchester City", "Premier League", 5, 8, 7.2, ""),
        ("Vitinha", "MF", "PSG", "Ligue 1", 8, 9, 7.5, ""),
        ("João Palhinha", "MF", "Bayern Munich", "Bundesliga", 2, 1, 6.9, ""),
        ("Otávio", "MF", "Al Nassr", "Saudi Pro League", 3, 4, 6.7, ""),
        ("Cristiano Ronaldo", "FW", "Al Nassr", "Saudi Pro League", 20, 5, 7.4, "Captain, 6th WC"),
        ("Rafael Leão", "FW", "AC Milan", "Serie A", 11, 7, 7.2, ""),
        ("Gonçalo Ramos", "FW", "PSG", "Ligue 1", 9, 3, 7.0, ""),
        ("Pedro Neto", "FW", "Chelsea", "Premier League", 4, 5, 6.9, ""),
        ("Francisco Conceição", "FW", "Juventus", "Serie A", 3, 4, 6.8, ""),
    ],
    "Congo DR": [
        ("Lionel Mpasi", "GK", "Rodez", "Ligue 2", 0, 0, 5.6, ""),
        ("Chancel Mbemba", "DF", "Marseille", "Ligue 1", 1, 0, 6.7, "Captain"),
        ("Axel Tuanzebe", "DF", "West Ham", "Premier League", 0, 0, 6.4, ""),
        ("Aaron Wan-Bissaka", "DF", "West Ham", "Premier League", 0, 2, 6.6, ""),
        ("Joris Kayembe", "DF", "Genk", "Belgian Pro League", 0, 1, 6.2, ""),
        ("Edo Kayembe", "MF", "Watford", "Championship", 2, 2, 6.4, ""),
        ("Samuel Moutoussamy", "MF", "Nantes", "Ligue 1", 1, 1, 6.3, ""),
        ("Grady Diangana", "MF", "West Brom", "Championship", 3, 2, 6.4, ""),
        ("Yoane Wissa", "FW", "Newcastle", "Premier League", 7, 3, 6.9, ""),
        ("Cédric Bakambu", "FW", "Galatasaray", "Turkish Super Lig", 6, 2, 6.6, ""),
        ("Meschak Elia", "FW", "Young Boys", "Swiss Super League", 4, 2, 6.4, ""),
    ],
    "Uzbekistan": [
        ("Utkir Yusupov", "GK", "Navbahor", "—", 0, 0, 5.3, ""),
        ("Farrukh Sayfiev", "DF", "Pakhtakor", "—", 0, 0, 5.4, ""),
        ("Khojiakbar Alijonov", "DF", "Pakhtakor", "—", 0, 0, 5.3, ""),
        ("Odiljon Hamrobekov", "MF", "Pakhtakor", "—", 1, 1, 5.5, ""),
        ("Jaloliddin Masharipov", "MF", "Al Nassr", "Saudi Pro League", 1, 2, 6.0, ""),
        ("Oston Urunov", "MF", "Persepolis", "Persian Gulf Pro League", 2, 1, 5.9, ""),
        ("Eldor Shomurodov", "FW", "Cagliari", "Serie A", 5, 2, 6.5, ""),
        ("Bobir Abdikholikov", "FW", "—", "—", 2, 0, 5.5, ""),
    ],
    "Colombia": [
        ("Camilo Vargas", "GK", "Atlas", "Liga MX", 0, 0, 6.4, ""),
        ("Daniel Muñoz", "DF", "Crystal Palace", "Premier League", 1, 3, 6.9, ""),
        ("Davinson Sánchez", "DF", "Galatasaray", "Turkish Super Lig", 1, 0, 6.7, ""),
        ("Jhon Lucumí", "DF", "Bologna", "Serie A", 0, 0, 6.6, ""),
        ("Johan Mojica", "DF", "Osasuna", "La Liga", 0, 1, 6.4, ""),
        ("Jefferson Lerma", "MF", "Crystal Palace", "Premier League", 2, 1, 6.7, ""),
        ("Richard Ríos", "MF", "Palmeiras", "Brazilian Serie A", 2, 2, 6.6, ""),
        ("James Rodríguez", "MF", "Minnesota United", "MLS", 6, 10, 7.2, "Captain"),
        ("Jhon Arias", "MF", "Fluminense", "Brazilian Serie A", 3, 3, 6.7, ""),
        ("Luis Díaz", "FW", "Bayern Munich", "Bundesliga", 15, 9, 7.5, ""),
        ("Rafael Santos Borré", "FW", "Werder Bremen", "Bundesliga", 7, 2, 6.7, ""),
        ("Jhon Durán", "FW", "Aston Villa", "Premier League", 6, 1, 6.8, ""),
        ("Luis Sinisterra", "FW", "Bournemouth", "Premier League", 4, 3, 6.7, ""),
    ],

    # === GROUP L ===
    "England": [
        ("Jordan Pickford", "GK", "Everton", "Premier League", 0, 0, 7.0, ""),
        ("Aaron Ramsdale", "GK", "Southampton", "Premier League", 0, 0, 6.6, ""),
        ("Dean Henderson", "GK", "Crystal Palace", "Premier League", 0, 0, 6.5, ""),
        ("John Stones", "DF", "Manchester City", "Premier League", 1, 0, 6.9, ""),
        ("Marc Guéhi", "DF", "Crystal Palace", "Premier League", 0, 0, 6.8, ""),
        ("Ezri Konsa", "DF", "Aston Villa", "Premier League", 0, 0, 6.7, ""),
        ("Kyle Walker", "DF", "Manchester City", "Premier League", 0, 2, 6.7, ""),
        ("Luke Shaw", "DF", "Manchester United", "Premier League", 0, 2, 6.6, ""),
        ("Rico Lewis", "DF", "Manchester City", "Premier League", 0, 2, 6.7, ""),
        ("Levi Colwill", "DF", "Chelsea", "Premier League", 0, 0, 6.6, ""),
        ("Declan Rice", "MF", "Arsenal", "Premier League", 4, 4, 7.3, ""),
        ("Jude Bellingham", "MF", "Real Madrid", "La Liga", 14, 10, 7.7, ""),
        ("Conor Gallagher", "MF", "Atlético Madrid", "La Liga", 4, 5, 7.0, ""),
        ("Kobbie Mainoo", "MF", "Manchester United", "Premier League", 2, 3, 6.9, ""),
        ("Morgan Gibbs-White", "MF", "Nottingham Forest", "Premier League", 15, 4, 7.1, ""),
        ("Harry Kane", "FW", "Bayern Munich", "Bundesliga", 22, 6, 7.6, "Captain"),
        ("Bukayo Saka", "FW", "Arsenal", "Premier League", 8, 7, 7.3, ""),
        ("Jarrod Bowen", "FW", "West Ham", "Premier League", 9, 11, 7.2, ""),
        ("Ollie Watkins", "FW", "Aston Villa", "Premier League", 11, 5, 7.1, ""),
        ("Anthony Gordon", "FW", "Newcastle", "Premier League", 12, 6, 7.3, ""),
    ],
    "Croatia": [
        ("Dominik Livaković", "GK", "Fenerbahçe", "Turkish Super Lig", 0, 0, 6.7, ""),
        ("Joško Gvardiol", "DF", "Manchester City", "Premier League", 3, 2, 7.2, ""),
        ("Josip Šutalo", "DF", "Ajax", "Eredivisie", 0, 0, 6.6, ""),
        ("Borna Sosa", "DF", "Ajax", "Eredivisie", 0, 2, 6.5, ""),
        ("Josip Stanišić", "DF", "Bayern Munich", "Bundesliga", 0, 1, 6.5, ""),
        ("Martin Erlić", "DF", "Sassuolo", "Serie A", 0, 0, 6.3, ""),
        ("Luka Modrić", "MF", "Real Madrid", "La Liga", 4, 7, 7.3, "Captain, 6th WC"),
        ("Mateo Kovačić", "MF", "Manchester City", "Premier League", 2, 3, 7.0, ""),
        ("Marcelo Brozović", "MF", "Al Nassr", "Saudi Pro League", 2, 3, 6.8, ""),
        ("Lovro Majer", "MF", "Wolfsburg", "Bundesliga", 3, 4, 6.8, ""),
        ("Martin Baturina", "MF", "Dinamo Zagreb", "Croatian HNL", 2, 3, 6.7, ""),
        ("Ivan Perišić", "FW", "PSV", "Eredivisie", 4, 4, 6.8, ""),
        ("Andrej Kramarić", "FW", "Hoffenheim", "Bundesliga", 7, 3, 6.9, ""),
        ("Ante Budimir", "FW", "Osasuna", "La Liga", 8, 1, 6.8, ""),
    ],
    "Ghana": [
        ("Lawrence Ati-Zigi", "GK", "St. Gallen", "Swiss Super League", 0, 0, 6.0, ""),
        ("Mohammed Salisu", "DF", "Monaco", "Ligue 1", 0, 0, 6.6, ""),
        ("Tariq Lamptey", "DF", "Brighton", "Premier League", 0, 1, 6.5, ""),
        ("Alexander Djiku", "DF", "Fenerbahçe", "Turkish Super Lig", 0, 0, 6.3, ""),
        ("Gideon Mensah", "DF", "Auxerre", "Ligue 1", 0, 0, 6.2, ""),
        ("Thomas Partey", "MF", "Villarreal", "La Liga", 2, 3, 7.0, "Captain"),
        ("Mohammed Kudus", "MF", "Tottenham", "Premier League", 10, 5, 7.2, "Injury doubt"),
        ("Elisha Owusu", "MF", "Auxerre", "Ligue 1", 1, 1, 6.3, ""),
        ("Ernest Nuamah", "MF", "Lyon", "Ligue 1", 3, 2, 6.5, ""),
        ("Iñaki Williams", "FW", "Athletic Bilbao", "La Liga", 6, 4, 6.9, ""),
        ("Antoine Semenyo", "FW", "Manchester City", "Premier League", 17, 4, 7.3, ""),
        ("Jordan Ayew", "FW", "Crystal Palace", "Premier League", 4, 2, 6.6, ""),
        ("Kamaldeen Sulemana", "FW", "Southampton", "Championship", 2, 2, 6.4, ""),
    ],
    "Panama": [
        ("Luis Mejía", "GK", "Nacional", "—", 0, 0, 5.7, ""),
        ("Fidel Escobar", "DF", "Saprissa", "—", 0, 0, 5.8, ""),
        ("Andrés Andrade", "DF", "LASK", "Austrian Bundesliga", 0, 0, 5.8, ""),
        ("Adalberto Carrasquilla", "MF", "Houston Dynamo", "MLS", 3, 5, 6.9, ""),
        ("Aníbal Godoy", "MF", "Nashville SC", "MLS", 1, 2, 6.3, ""),
        ("Édgar Bárcenas", "MF", "Mazatlán", "Liga MX", 2, 2, 6.4, ""),
        ("José Fajardo", "FW", "—", "—", 2, 1, 6.0, ""),
        ("Ismael Díaz", "FW", "Universidad Católica", "—", 1, 0, 5.9, ""),
        ("Cecilio Waterman", "FW", "—", "—", 1, 0, 5.8, ""),
    ],
}

# ============================================================
# Merge into world_cup_players.json structure
# ============================================================
print("Building full squads...")
total_players = 0
new_players_added = 0

for gn in wp["groups"]:
    for nat in wp["groups"][gn]["teams"]:
        existing_names = {p["name"] for p in wp["groups"][gn]["teams"][nat]["players"]}
        if nat in SQUADS:
            for (name, pos, club, league, g2526, a2526, rating, notes) in SQUADS[nat]:
                if name not in existing_names:
                    wp["groups"][gn]["teams"][nat]["players"].append({
                        "name": name,
                        "position": pos,
                        "age": None,
                        "caps": None,
                        "club": club,
                        "league": league,
                        "goals_2425": None,
                        "goals_2526": g2526,
                        "assists_2526": a2526,
                        "rating": rating,
                        "notes": notes if notes else "",
                    })
                    new_players_added += 1
                total_players += 1

# Count total
final_total = sum(len(td["players"]) for gn in wp["groups"] for td in wp["groups"][gn]["teams"].values())
print(f"Players: {final_total} total, {new_players_added} new (previously had 147)")

# Also update supplement to remove unmatched players
existing_names_set = set()
for gn in wp["groups"]:
    for nat, td in wp["groups"][gn]["teams"].items():
        for p in td["players"]:
            existing_names_set.add((p["name"], nat))

# Update supplement
supp_players = supp.get("players", [])
matched_supp = [p for p in supp_players if (p["name"], p.get("nation", "")) in existing_names_set]
print(f"Supplement: {len(matched_supp)} matched, {len(supp_players) - len(matched_supp)} removed (not in squad)")
supp["players"] = matched_supp

# Save
wp["_meta"]["total_players"] = final_total
wp["_meta"]["last_updated"] = "2026-06-11 (full squads)"
wp["_meta"]["note"] = "Expanded from 147 to full squads using official FIFA squad lists"

with open(f"{DATA_DIR}/world_cup_players.json", "w", encoding="utf-8") as f:
    json.dump(wp, f, indent=2, ensure_ascii=False)

with open(f"{DATA_DIR}/player_stats_supplement.json", "w", encoding="utf-8") as f:
    json.dump(supp, f, indent=2, ensure_ascii=False)

# Summary per team
print("\nFinal squad sizes:")
for gn in sorted(wp["groups"].keys()):
    for nat in sorted(wp["groups"][gn]["teams"].keys()):
        n = len(wp["groups"][gn]["teams"][nat]["players"])
        print(f"  Group {gn}: {nat:<22s} {n} players")

print(f"\nTotal: {final_total} players")
